typography_spectrum: 0.9363524198997766
color:
  brandStrength: 0.357813339214772
  lightness: 0.45190577302128077
  saturation: 0.9329189646523446
  rhythmicContrast: 0.4394203971605748
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.5148054210003465
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: "Beyond Beliefs\_"
description: "Create your future. \_Your way!"
