typography_spectrum: 0.9992235798854381
color:
  brandStrength: 0.08879983075894415
  lightness: 0.17471508239395916
  saturation: 0.10224983328953385
  rhythmicContrast: 0.6001652500126511
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.43516468326561153
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
  - name: Access Bars Consciousness
    id: 49babb5b-8fa4-4d08-88e2-79830838ceba
    type: content
title: Debbie Harding
description: "Create your future. \_Your way!"
