typography_spectrum: 0.02853263379074633
color:
  brandStrength: 0.35351923713460565
  lightness: 0.8945769818965346
  saturation: 0.04591964744031429
  rhythmicContrast: 0.07005331409163773
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.5880162653047591
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: Debbie Harding
description: "Create your future. \_Your way!"
