typography_spectrum: 0.26441508741118014
color:
  brandStrength: 0.3245287674944848
  lightness: 0.2391342711634934
  saturation: 0.43159761745482683
  rhythmicContrast: 0.7209138909820467
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.4181976888794452
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: Debbie Harding
description: "Create your future. \_Your way!"
