typography_spectrum: 0.19301060563884676
color:
  brandStrength: 0.18168328399769962
  lightness: 0.583806101931259
  saturation: 0.9868681251537055
  rhythmicContrast: 0.28576291515491903
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
layout_spectrum: 0.8716674633324146
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: "Beyond Beliefs\_"
description: "Create your future. \_Your way!"
