typography_spectrum: 0.6675653061829507
color:
  brandStrength: 0.21090020658448339
  lightness: 0.5614443116355687
  saturation: 0.6748983592260629
  rhythmicContrast: 0.5336662793997675
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
layout_spectrum: 0.5905562257394195
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: Debbie Harding
description: "Create your future. \_Your way!"
