typography_spectrum: 0.24139970890246332
color:
  brandStrength: 0.4120556437410414
  lightness: 0.2979750765953213
  saturation: 0.5779612364713103
  rhythmicContrast: 0.6494554623495787
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.2815413314383477
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: "Beyond Beliefs\_"
description: "Create your future. \_Your way!"
