layout_spectrum: 0.824742734941036
typography_spectrum: 0.6692674073749361
color:
  brandStrength: 0.33468739922997537
  lightness: 0.8490739260990136
  saturation: 0.9716385655444447
  rhythmicContrast: 0.9013506101158513
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
author:
  name: Debbie Harding
  email: hardingdebs@gmail.com
  url: 'http://www.thetadebharding.com.au'
name: Beyond Beliefs
navigation:
  - name: ThetaHealing & Access Bars Consciousness
    url: 'http://www.thetadebharding.com.au/'
    type: external
title: "Beyond Beliefs\_"
description: "Create your future. \_Your way!"
content: []
github: true
